### ISSUE TITLE
Splash Screen 

### ISSUE THREAD

**Issue by InsanePeter** [InsanePeter/reconnect#1]
Criar um splash screen para o app, onde mostrara uma screen quando o app carregar no inicio, durante alguns segundos , sugiro o nome do app na hora de carregar
alguns links que podem ajudar como guia
http://www.thiagovespa.com.br/blog/2012/10/02/criando-uma-splash-screen-em-android/
http://www.coderefer.com/android-splash-screen-example-tutorial/
http://www.androidhive.info/2013/07/how-to-implement-android-splash-screen-2/

**Comment by clebermatheus** [comment]
Acredito que está pronto, então estou fechando este issue.
